FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY streamlit streamlit

EXPOSE 8501

CMD ["streamlit", "run", "streamlit/streamlit_app.py"]
